batch_size: 28
train_steps: 200
context length: 250
num_tasks: 40000
output_dir: ../outputs/GPT2/240619_201625.535c3c_upperTriA_gauss_C
checkpoint_callback /home/sultand/mop_modifications/streamlined_mop/outputs/GPT2/240619_201625.535c3c_upperTriA_gauss_C/checkpoints
ckpt_path: ../outputs/GPT2/240619_201625.535c3c_upperTriA_gauss_C/checkpoints/step=200.ckpt
Traceback (most recent call last):
  File "/home/sultand/mop_modifications/streamlined_mop/src/data_train.py", line 122, in <module>
    train_gpt2(model, config, output_dir) # train the model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sultand/mop_modifications/streamlined_mop/src/train.py", line 50, in train_gpt2
    trainer = pl.Trainer(
              ^^^^^^^^^^^
  File "/home/sultand/.conda/envs/mop/lib/python3.12/site-packages/pytorch_lightning/utilities/argparse.py", line 70, in insert_env_defaults
    return fn(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/sultand/.conda/envs/mop/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 400, in __init__
    self._accelerator_connector = _AcceleratorConnector(
                                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sultand/.conda/envs/mop/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 143, in __init__
    self._accelerator_flag = self._choose_gpu_accelerator_backend()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sultand/.conda/envs/mop/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 353, in _choose_gpu_accelerator_backend
    raise MisconfigurationException("No supported gpu backend found!")
lightning_fabric.utilities.exceptions.MisconfigurationException: No supported gpu backend found!